device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjE4MTUxNzQ1LCJpYXQiOjE1ODY2MTU3NDUsImlzcyI6InN0cyIsImp0aSI6Ind1Y2FHN1EzQ1dUSUZwNjViRWt5U3UiLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLWQzNmNiMGM3LTRmNjAtNDM1OC1hYTY5LTA2OGNkNzVmZTFmMCIsIm93dXIiOiJ1c3ItSEZJdVAxR0QiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC1sM3NIeEtJV3A1IiwidHlwIjoiSUQifQ.AN7fBXO07Rk2y-6ywpWHB41BUbS-rTNRZ97qMG6mRD438OpJnFJO_FJt6DOa4FiZkRwDyLUSYr9TLo-Y7PcCyvcLOCO-O7bhycnUvxbGJS2nGao7sBl-GBZDgEDij2wGmBq-7D8FyLt7eEjzVenIQr4bp98ZdubbnXFDIkXDXFI
mqttbroker:
    address: 192.168.21.29:1883
registry:
    service_address: 192.168.21.29:8889
    middle_credential: 2240dd54-6d33-4814-aef8-65d104f8b626