device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjE3NzExOTQ0LCJpYXQiOjE1ODYxNzU5NDQsImlzcyI6InN0cyIsImp0aSI6ImdqN3pnaTdlTTJoVEVwSTVJWW1XTVIiLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLWIyN2YyOWVhLTFmZmYtNGJjYS1hNjlkLTAyYzY1NjJiNTFiYyIsIm93dXIiOiJ1c3ItV0w4T2JWcGIiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC1xMXFSV201WkVtIiwidHlwIjoiSUQifQ.T0lb79TU8JR8r6k5Dm6pk-qY2nvuY5meew5LRRXBn5AEQexdzxhkZV7TzKpSCJgx4wiDmDKkukJVOdoMHL-OTsg0XnMcI4QNoQ7vIs7Wnr9Q8LvtCNODbfqY8tWYoGzqdcYfaNrKZUm4-_TFgWVcBPlpYhJzI-5bGDq5om7aZeQ
mqttbroker:
    address: 192.168.21.29:1883
registry:
    service_address: 192.168.21.22:8889
    middle_credential: 0d9ff70b-8a3a-4372-a5fa-6c59a5fe2829