device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjIyMTg5NzU4LCJpYXQiOjE1OTA2NTM3NTgsImlzcyI6InN0cyIsImp0aSI6InE3dHVYUFQ0WnM5eDZsMFBka1c4RjciLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLWY3ODZjZDQwLTViNTYtNGU0Zi1iN2VjLTU4MGIzODJkNDk1YyIsIm93dXIiOiJ1c3ItSEZJdVAxR0QiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC1sM3NIeEtJV3A1IiwidHlwIjoiSUQifQ.4Fw-RNUklUTiZxpVgHE2Bfi8PNURiPaNLz8eUF7dHuA9cTdWP_lfEK86wzWVYVM-fnLHm0HazX4h0CCS3xUzKcirMmDoSz8nHKESuB0RwSaLJkBz9ZeBZj7d11Ah6iKcVLZ1KvRJN1jZKGs3gVvRc3r03RWMpU3Y30PlhU81LvI
    auto_reconnect: true
mqttbroker:
    address_mqtt: 192.168.21.29:1883
    address_mqtts: iot.qingcloud.com:1884
registry:
    service_address: 192.168.21.29:8889
    middle_credential: 20362c80-6332-49ce-8e0a-4daaf514c75a