device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjIzMjMzOTE0LCJpYXQiOjE1OTE2OTc5MTQsImlzcyI6InN0cyIsImp0aSI6InM5aVM5UWdxS1E1bGxqZmxBdjJCNFMiLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLWYwMTE3YzA1LTNiMzgtNDUxOS04YjYwLTZhMzhkM2Q4Yzk3MiIsIm93dXIiOiJ1c3ItaXVYYmkyNnoiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC15a0xITFJvb1hGIiwidHlwIjoiSUQifQ.TO9RUF_qE8UZwgLYLTGa9-7zqB0elA6qdMk9UpIUdmFxGjs9fH_23_z2KIg-H7bgRgs3bWFU5XS-QxbJxd3X4AVx8or-XrSig0cvpDmtjWyamR9ExjLH-djeA9vBh_vvL7hWBehG4IDPxsGnRfnbzwOtOIjzajsQLhbDlz7lwQY
    auto_reconnect: true
mqttbroker:
    address_mqtt: iot.qingcloud.com:1883
    address_mqtts: iot.qingcloud.com:1884
registry:
    service_address: iot.api.qingcloud.com
    middle_credential: e9e6e9b1-f8c4-4c74-9dfa-ee93f13c6005