device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjE5NDA0Njg2LCJpYXQiOjE1ODc4Njg2ODYsImlzcyI6InN0cyIsImp0aSI6IkZTNU5RcWlCWThIYWV3NFF5d0w0TEwiLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLTU1YmRmMjEzLTQ1NDctNDlhOC04ODVkLTU1MGNlNjExYzI3YSIsIm93dXIiOiJ1c3ItaXVYYmkyNnoiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC15a0xITFJvb1hGIiwidHlwIjoiSUQifQ.KQ-dbVPU-DYgU1wLtIPyNVzNkWDwEJGhZql9OPu9zPf7RIji6ATHNhhUrtuLtMsTEpPebK4nIoI9wXwACXCyICBwEeH1E1RR-lYKUNWWxWVuxn26eBy9YpEmmYSPRzDrYA3WQf0bPilzDQ8YhiJV03Ud_fRDElzS1QgARzbLZRY
    auto_reconnect: false
mqttbroker:
    address_mqtt: iot.qingcloud.com:1883
    address_mqtts: iot.qingcloud.com:1884
registry:
    service_address: iot-api.qingcloud.com
    middle_credential: f364439e-f5e5-454a-8753-32931300d0f4