device:
    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY3IiOiIxIiwiYXVkIjoiaWFtIiwiYXpwIjoiaWFtIiwiZXhwIjoxNjE5NzU0MDg0LCJpYXQiOjE1ODgyMTgwODQsImlzcyI6InN0cyIsImp0aSI6ImNXRjQ3Wk5VQ1FDZXFQeE1ra1pDOE0iLCJuYmYiOjAsIm9yZ2kiOiJpb3RkLTZlNTczNmIzLTA3MTItNDIxOS1iMTBlLTkyYzc3N2Y4OGE0ZSIsIm93dXIiOiJ1c3ItaXVYYmkyNnoiLCJzdWIiOiJzdHMiLCJ0aGlkIjoiaW90dC15a0xITFJvb1hGIiwidHlwIjoiSUQifQ.ZK7vLtd2cMUHGF5EfziHqh9jxGS5DlGMsDEgOWIDW8n-NKJ1IZVDNZ-6yMtiqQyhvgLseZxOmbAhBq3aolhrVyCilNgVmZX2RnADa0Q48QrSBvrak-mtfL0KIvDG7zi5itWnKMSXoT5XKz1cpLPbIxMwZMSKNLZMRH35KCPSxhE
    auto_reconnect: true
mqttbroker:
    address_mqtt: iot.qingcloud.com:1883
    address_mqtts: iot.qingcloud.com:1884
registry:
    service_address: iot.api.qingcloud.com
    middle_credential: e9e6e9b1-f8c4-4c74-9dfa-ee93f13c6005